[package]
name = "mdast-words-count"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
humansize = "2.1.3"
markdown = "1.0.0-alpha.12"
num-format = "0.4.4"
walkdir = "2.3.3"
words-count = "0.1.5"
